#!/usr/bin/env bash
# Installs nginx, listening on port 80, returns a page containing the string
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo rm /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
sudo service nginx reload
