#!/usr/bin/env bash
#Display Best School in 10 interations
#But bad luck on 4th and good luck on 8th
i="1"
while [ $i -lt 11 ]
do
	if [ $i == 4 ]
		then echo "bad luck"
	elif [ $i == 8 ]
		then echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
